### ISSUE TITLE
Timeseries clustering pipeline fails

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1372]
The timeseries clustering pipeline from Distil generates the following error in the TA2 when run:

```
INFO - 2019-12-10 18:04:25,602 - v-master-7728ff7 - distil.TaskManager - Initialized TaskManager
DEBUG:d3m.namespace:Loading entry point 'data_preprocessing.data_cleaning.DistilTimeSeriesFormatter'.
ERROR - 2019-12-10 18:04:25,619 - v-master-7728ff7 - distil.server.ServerServicer - Request not properly formatted, aborting gRPC call: Unable to get primitive '1c4aed23-f3d3-4e6b-9710-009a9bc9b694'.
Traceback (most recent call last):
  File "/home/chris/dev/git_work/distil-auto-ml/server/server.py", line 26, in _unary_unary_interceptor
    result = func(request)
  File "/home/chris/dev/git_work/distil-auto-ml/server/task_manager.py", line 58, in SearchSolutions
    search_template_obj = api_utils.decode_pipeline_description(message.template, pipeline.Resolver(load_all_primitives=False))
  File "/home/chris/dev/git_work/distil-auto-ml/api/utils.py", line 797, in decode_pipeline_description
    step = pipeline._get_step_class(metadata_base.PipelineStepType.PRIMITIVE)(primitive_description=decode_primitive(step_description.primitive.primitive), resolver=resolver)
  File "/home/chris/dev/git_work/d3m/d3m/metadata/pipeline.py", line 487, in __init__
    primitive = self.resolver.get_primitive(primitive_description)
  File "/home/chris/dev/git_work/d3m/d3m/metadata/pipeline.py", line 104, in get_primitive
    primitive = self._get_primitive(primitive_description)
  File "/home/chris/dev/git_work/d3m/d3m/metadata/pipeline.py", line 197, in _get_primitive
    return index.get_primitive_by_id(primitive_description['id'])
  File "/home/chris/dev/git_work/d3m/d3m/index.py", line 141, in get_primitive_by_id
    raise exceptions.InvalidArgumentValueError("Unable to get primitive '{primitive_id}'.".format(primitive_id=primitive_id))
d3m.exceptions.InvalidArgumentValueError: Unable to get primitive '1c4aed23-f3d3-4e6b-9710-009a9bc9b694'.
```

**Comment by cdbethune** [comment]
2019-11 version of Sloth primitive wasn't really setup to run with current version of long form timeseries.  Our fork was updated (https://github.com/cdbethune/D3M-Unsupervised/tree/ts-cluster-fixes) with fixes, and the new version is now being built into distil-auto-ml.  There were a few small changes to the definition of the pipeline made in distil-compute as a consequence of the primitive update as well.
