### ISSUE TITLE
Predicted results for images

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1493]
Some work has been done to support predicted results with image workflows, but it still isn't complete.  With `coil-20` we currently get the follow error when running against its test data:

```
[ Feb 24 09:51:44 ] [ INFO ] generating predictions for fitted solution ID bb3d603a-bb33-40f8-9a54-bebcc528f47f (api/task/prediction.go:63)
[ Feb 24 09:51:44 ] [ INFO ] augment inference dataset fields (api/task/prediction.go:205)
[ Feb 24 09:51:44 ] [ WARN ] field 'd3mIndex' not found in source dataset (api/task/prediction.go:232)
[ Feb 24 09:51:44 ] [ WARN ] field 'image' not found in source dataset (api/task/prediction.go:232)
[ Feb 24 09:51:44 ] [ WARN ] field 'label' not found in source dataset (api/task/prediction.go:232)
[ Feb 24 09:51:44 ] [ INFO ] rewriting inference dataset to match source dataset structure (api/task/prediction.go:249)
2020/02/24 09:51:44 http: panic serving [::1]:59926: runtime error: invalid memory address or nil pointer dereference
goroutine 178 [running]:
net/http.(*conn).serve.func1(0xc0001b0140)
        /usr/lib/go/src/net/http/server.go:1767 +0x139
panic(0xd07be0, 0x15784a0)
        /usr/lib/go/src/runtime/panic.go:679 +0x1b2
github.com/uncharted-distil/distil/api/task.augmentPredictionDataset(0xc000884000, 0x6324, 0x7e00, 0x0, 0x0, 0x0, 0x1, 0x1, 0xc0003961a8, 0xe36859, ...)
        /home/chris/dev/git_work/distil/api/task/prediction.go:251 +0x865
github.com/uncharted-distil/distil/api/task.Predict(0xc000acb860, 0xc00030eb40, 0x29, 0xc0001a3e20)
        /home/chris/dev/git_work/distil/api/task/prediction.go:77 +0x158
github.com/uncharted-distil/distil/api/routes.PredictionsHandler.func1(0xf697e0, 0xc000ab8a80, 0xc001054400)
        /home/chris/dev/git_work/distil/api/routes/predictions.go:187 +0x7b6
net/http.HandlerFunc.ServeHTTP(0xc000434b80, 0xf697e0, 0xc000ab8a80, 0xc001054400)
        /usr/lib/go/src/net/http/server.go:2007 +0x44
goji.io/v3.dispatch.ServeHTTP(0xf697e0, 0xc000ab8a80, 0xc001054400)
        /home/chris/dev/go_workspace/pkg/mod/goji.io/v3@v3.0.0/dispatch.go:17 +0xba
github.com/uncharted-distil/distil/api/middleware.Gzip.func1(0x7fd930531088, 0xc000e060c0, 0xc001054400)
        /home/chris/dev/git_work/distil/api/middleware/gzip.go:57 +0x21f
net/http.HandlerFunc.ServeHTTP(0xc0004550a0, 0x7fd930531088, 0xc000e060c0, 0xc001054400)
        /usr/lib/go/src/net/http/server.go:2007 +0x44
github.com/uncharted-distil/distil/api/middleware.Log.func1(0xf693a0, 0xc000192540, 0xc001054400)
        /home/chris/dev/git_work/distil/api/middleware/log_http.go:37 +0x2b0
net/http.HandlerFunc.ServeHTTP(0xc0004550c0, 0xf693a0, 0xc000192540, 0xc001054400)
        /usr/lib/go/src/net/http/server.go:2007 +0x44
goji.io/v3.(*Mux).ServeHTTP(0xc000167580, 0xf693a0, 0xc000192540, 0xc001054000)
        /home/chris/dev/go_workspace/pkg/mod/goji.io/v3@v3.0.0/mux.go:74 +0x1cd
net/http.serverHandler.ServeHTTP(0xc0001921c0, 0xf693a0, 0xc000192540, 0xc001054000)
        /usr/lib/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0001b0140, 0xf6d5a0, 0xc0000b9100)
        /usr/lib/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2927 +0x38e
```

**Comment by cdbethune** [comment]
Covered by #1510
