### ISSUE TITLE
Error when classification target has empty labels

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1552]
Importing the insurgent crime dataset and predicting the `state_sponsored` field resulted in the following error below from the ta2.  While this is likely an issue at that level, rather than a TA3 / import problem, diagnoses needs to start at the top.  The issue is likely tied to predicting against empty labels.

```
/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:915: RuntimeWarning: Number of classes in training fold (2) does not match total number of classes (3). Results may not be appropriate for your use case. To fix this, use a cross-validation technique resulting in properly stratified folds
  RuntimeWarning)
WARNING - 2020-04-07 11:34:04,248 - v-master-ee35a0b - distil - Exception running task ID 84b3c9f9-e5a4-4b10-b76a-5d5bc2292956: Step 27 for pipeline  failed.
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 889, in _fit_and_predict
    estimator.classes_, predictions, n_classes, method)
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 935, in _enforce_prediction_order
    len(classes), n_classes, recommendation))
ValueError: Only 2 class/es in training fold, but 3 in overall dataset. This is not supported for decision_function with imbalanced folds. To fix this, use a cross-validation technique resulting in properly stratified folds
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 941, in _do_run_step
    self._run_step(step)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 931, in _run_step
    self._run_primitive(step)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 839, in _run_primitive
    multi_call_result = self._call_primitive_method(primitive.fit_multi_produce, fit_multi_produce_arguments)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 914, in _call_primitive_method
    raise error
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 910, in _call_primitive_method
    result = method(**arguments)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/base.py", line 529, in fit_multi_produce
    return self._fit_multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, inputs=inputs, outputs=outputs)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/base.py", line 556, in _fit_multi_produce
    fit_result = self.fit(timeout=timeout, iterations=iterations)
  File "/home/chris/dev/git_work/distil-primitives/distil/primitives/text_encoder.py", line 130, in fit
    self._outputs)  # requires fit transform to fit SVM on vectorizer results
  File "/home/chris/dev/git_work/distil-primitives/distil/preprocessing/transformers.py", line 89, in fit_transform
    out = cross_val_predict(self._model, Xv, y, method='decision_function', n_jobs=3, cv=3)
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 789, in cross_val_predict
    for train, test in cv.split(X, y, groups))
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
ValueError: Only 2 class/es in training fold, but 3 in overall dataset. This is not supported for decision_function with imbalanced folds. To fix this, use a cross-validation technique resulting in properly stratified folds

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 123, in fit_task
    fitted_runtime, result = ex_pipeline.fit(pipeline_obj, problem_obj, train_dataset, is_standard_pipeline=run_as_standard)
  File "/home/chris/dev/git_work/distil-auto-ml/processing/pipeline.py", line 296, in fit
    raise result.error
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 972, in _run
    self._do_run()
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 958, in _do_run
    self._do_run_step(step)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 950, in _do_run_step
    ) from error
d3m.exceptions.StepFailedError: Step 27 for pipeline  failed.
INFO - 2020-04-07 11:34:05,255 - v-master-ee35a0b - distil - Starting distil task ID 9152bb11-7df5-475b-bb82-992a71884b04
WARNING:d3m.metadata.pipeline_run:Configuration environment variable not set: D3MCPU
WARNING:d3m.metadata.pipeline_run:Configuration environment variable not set: D3MRAM
ERROR - 2020-04-07 11:34:05,460 - v-master-ee35a0b - distil.server.ServerServicer - Unexpected error occured, aborting gRPC call: FitSolution task didn't complete successfully
Traceback (most recent call last):
  File "/home/chris/dev/git_work/distil-auto-ml/server/server.py", line 52, in _unary_stream_interceptor
    for message in func(request):
  File "/home/chris/dev/git_work/distil-auto-ml/server/task_manager.py", line 295, in GetFitSolutionResults
    raise RuntimeError("FitSolution task didn't complete successfully")
RuntimeError: FitSolution task didn't complete successfully
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=/home/chris/dev/git_work/d3m, universal_newlines=False, shell=None)
WARNING:d3m.metadata.pipeline_run:Docker image environment variable not set: D3M_BASE_IMAGE_NAME
WARNING:d3m.metadata.pipeline_run:Docker image environment variable not set: D3M_BASE_IMAGE_DIGEST
WARNING:d3m.metadata.pipeline_run:Docker image environment variable not set: D3M_IMAGE_NAME
WARNING:d3m.metadata.pipeline_run:Docker image environment variable not set: D3M_IMAGE_DIGEST
/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:915: RuntimeWarning: Number of classes in training fold (2) does not match total number of classes (3). Results may not be appropriate for your use case. To fix this, use a cross-validation technique resulting in properly stratified folds
  RuntimeWarning)
WARNING - 2020-04-07 11:34:06,794 - v-master-ee35a0b - distil - Exception running task ID 9152bb11-7df5-475b-bb82-992a71884b04: Step 27 for pipeline  failed.
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 889, in _fit_and_predict
    estimator.classes_, predictions, n_classes, method)
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 935, in _enforce_prediction_order
    len(classes), n_classes, recommendation))
ValueError: Only 2 class/es in training fold, but 3 in overall dataset. This is not supported for decision_function with imbalanced folds. To fix this, use a cross-validation technique resulting in properly stratified folds
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 941, in _do_run_step
    self._run_step(step)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 931, in _run_step
    self._run_primitive(step)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 839, in _run_primitive
    multi_call_result = self._call_primitive_method(primitive.fit_multi_produce, fit_multi_produce_arguments)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 914, in _call_primitive_method
    raise error
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 910, in _call_primitive_method
    result = method(**arguments)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/base.py", line 529, in fit_multi_produce
    return self._fit_multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, inputs=inputs, outputs=outputs)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/base.py", line 556, in _fit_multi_produce
    fit_result = self.fit(timeout=timeout, iterations=iterations)
  File "/home/chris/dev/git_work/distil-primitives/distil/primitives/text_encoder.py", line 130, in fit
    self._outputs)  # requires fit transform to fit SVM on vectorizer results
  File "/home/chris/dev/git_work/distil-primitives/distil/preprocessing/transformers.py", line 89, in fit_transform
    out = cross_val_predict(self._model, Xv, y, method='decision_function', n_jobs=3, cv=3)
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 789, in cross_val_predict
    for train, test in cv.split(X, y, groups))
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
ValueError: Only 2 class/es in training fold, but 3 in overall dataset. This is not supported for decision_function with imbalanced folds. To fix this, use a cross-validation technique resulting in properly stratified folds

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 123, in fit_task
    fitted_runtime, result = ex_pipeline.fit(pipeline_obj, problem_obj, train_dataset, is_standard_pipeline=run_as_standard)
  File "/home/chris/dev/git_work/distil-auto-ml/processing/pipeline.py", line 296, in fit
    raise result.error
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 972, in _run
    self._do_run()
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 958, in _do_run
    self._do_run_step(step)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 950, in _do_run_step
    ) from error
d3m.exceptions.StepFailedError: Step 27 for pipeline  failed.
ERROR - 2020-04-07 11:34:08,471 - v-master-ee35a0b - distil.server.ServerServicer - Unexpected error occured, aborting gRPC call: FitSolution task didn't complete successfully
Traceback (most recent call last):
  File "/home/chris/dev/git_work/distil-auto-ml/server/server.py", line 52, in _unary_stream_interceptor
    for message in func(request):
  File "/home/chris/dev/git_work/distil-auto-ml/server/task_manager.py", line 295, in GetFitSolutionResults
    raise RuntimeError("FitSolution task didn't complete successfully")
RuntimeError: FitSolution task didn't complete successfully
```
The dataset is not part of the standard D3M distribution, but I can provide the CSV for import.  The input state that lead to the error is as follows:

![image](https://user-images.githubusercontent.com/8959554/78690044-f8b8b880-78c4-11ea-89bd-04e8f27aaa06.png)

**Comment by cdbethune** [comment]
Is this still an issue after the various import changes?
