### ISSUE TITLE
PCA ranking exception during import

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#1933]
When importing the 185_baseball tabular dataset via the UI we see the following error reported by the pca ranking step:

```
distil-auto-ml_1  | ERROR:root:Failed
distil-auto-ml_1  | Traceback (most recent call last):
distil-auto-ml_1  |   File "/usr/local/lib/python3.6/dist-packages/punk/feature_selection/pca.py", line 47, in rank_features
distil-auto-ml_1  |     .values, axis=0))
distil-auto-ml_1  |   File "/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_data.py", line 1705, in normalize
distil-auto-ml_1  |     estimator='the normalize function', dtype=FLOAT_DTYPES)
distil-auto-ml_1  |   File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 594, in check_array
distil-auto-ml_1  |     context))
distil-auto-ml_1  | ValueError: Found array with 0 feature(s) (shape=(1073, 0)) while a minimum of 1 is required by the normalize function.
distil-auto-ml_1  | INFO - 2020-09-16 18:09:08,144 - v-master-e825c94 - distil.TaskManager - Initialized TaskManager
distil-auto-ml_1  | INFO - 2020-09-16 18:09:08,162 - v-master-e825c94 - distil.TaskManager - Initialized TaskManager
distil-auto-ml_1  | INFO - 2020-09-16 18:09:09,139 - v-master-e825c94 - distil - Starting produce task ID f842b28d-5be3-4ad6-81a1-d12b92492a1f
distil-auto-ml_1  | INFO - 2020-09-16 18:09:15,936 - v-master-e825c94 - distil.TaskManager - Initialized TaskManager
```

The ingest completes, but it is unclear what the source of the error is.

**Comment by Zac-hills** [comment]
![image](https://user-images.githubusercontent.com/25306965/94300117-87ce9100-ff36-11ea-8ca2-96c2cc77b94e.png)
It is still working, it has an issue with one feature.
![image](https://user-images.githubusercontent.com/25306965/94300251-b8aec600-ff36-11ea-9a9b-dbf265b26c6e.png)
This is the feature it has an issue with. I will take a look into how we are generating the json for this particular feature.
