### ISSUE TITLE
Index out of range when predicting

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2121]
Running predictions on a trained model (I used auto) results in the following exception:

```
[ Dec 10 15:45:28 ] [ INFO ] rewriting prediction dataset to match source dataset structure (api/task/prediction.go:426)
panic: runtime error: index out of range [0] with length 0

goroutine 8100144 [running]:
github.com/uncharted-distil/distil/api/task.augmentPredictionDataset(0xc0003c8000, 0x65, 0x80, 0xc000f54230, 0x9, 0x9, 0x1a5d948, 0x0, 0x0, 0x0, ...)
        /home/chris/dev/git_work/distil/api/task/prediction.go:442 +0x102a
github.com/uncharted-distil/distil/api/task.(*predictionDataset).CreateDataset(0xc0004c60b8, 0xc000c2c390, 0x30, 0xc000c23140, 0x12, 0xc00020f800, 0x2, 0x2, 0x3fe999999999999a)
        /home/chris/dev/git_work/distil/api/task/prediction.go:138 +0x16d
github.com/uncharted-distil/distil/api/task.CreateDataset(0xc000c23140, 0x12, 0x11e6ce0, 0xc0004c60b8, 0xc000c22440, 0x1d, 0xc00020f800, 0x1, 0x30, 0xc00065f5c0, ...)
        /home/chris/dev/git_work/distil/api/task/dataset.go:75 +0x3a2
github.com/uncharted-distil/distil/api/task.Predict(0xc000210e40, 0xc00033b1f0, 0xc000210e40, 0x11e6c40)
        /home/chris/dev/git_work/distil/api/task/prediction.go:197 +0x18f5
github.com/uncharted-distil/distil/api/ws.handlePredict(0xc0006168e0, 0xc0000ac230, 0xc00037ad80, 0xc00039c9a0, 0xc00039c9c0, 0xc00037adb0, 0xc000ed46e0)
        /home/chris/dev/git_work/distil/api/ws/pipeline.go:431 +0x8b3
github.com/uncharted-distil/distil/api/ws.handleMessage(0xc0006168e0, 0xc0000ac230, 0xc00037ad80, 0xc00039c9a0, 0xc00039c9c0, 0xc00037adb0, 0xc000ed46e0)
        /home/chris/dev/git_work/distil/api/ws/pipeline.go:107 +0x1a5
created by github.com/uncharted-distil/distil/api/ws.handleSolutionMessage.func1
        /home/chris/dev/git_work/distil/api/ws/pipeline.go:92 +0x211
exit status 2
[
```

**Comment by phorne-uncharted** [comment]
A previous PR fixed a lot of predictions related issues, including this one where the header from a tabular dataset prediction was not being processed properly.
