### ISSUE TITLE
Panic splitting pre-featurized datasets

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2185]
On a pre-featurized dataset the following error is produced when creating models:

```
[ Jan 14 17:21:19 ] [ INFO ] checking folders `/home/chris/outputs/locust_medium_d3m-c482871493a0d0a4/train/datasetDoc.json` & `/home/chris/outputs/locust_medium_d3m-c482871493a0d0a4/test/datasetDoc.json` to see if the dataset has been previously split (api/compute/split.go:463)
panic: runtime error: index out of range [-1]

goroutine 25494027 [running]:
github.com/uncharted-distil/distil/api/compute.(*stratifiedSplitter).splitCategories(0xc0217d52c0, 0xffffffffffffffff, 0xc079544018, 0x439c, 0x439c, 0xc0012466b7)
        /home/chris/dev/git_work/distil/api/compute/split.go:254 +0x285
github.com/uncharted-distil/distil/api/compute.(*stratifiedSplitter).split(0xc0217d52c0, 0xc079544000, 0x439d, 0x439d, 0x439d, 0x439d, 0x0, 0x0, 0x0, 0x0, ...)
        /home/chris/dev/git_work/distil/api/compute/split.go:279 +0x315
github.com/uncharted-distil/distil/api/compute.SplitDataset(0xc004874190, 0x4a, 0x11f8b00, 0xc0217d52c0, 0x4a, 0xc000985401, 0xc0012466b7, 0x7, 0x3fe322d0e5604189, 0x0)
        /home/chris/dev/git_work/distil/api/compute/split.go:331 +0x475
github.com/uncharted-distil/distil/api/compute.(*SolutionRequest).PersistAndDispatch(0xc0010dbe60, 0xc0003101e0, 0x1219580, 0xc000eaa330, 0x1217c60, 0xc000eaa2d0, 0x1219ba0, 0xc000eaa2a0, 0x3fe999999999999a, 0x10001)
        /home/chris/dev/git_work/distil/api/compute/solution_request.go:758 +0xa0f
github.com/uncharted-distil/distil/api/ws.handleCreateSolutions(0xc000b74040, 0xc0003101e0, 0xc0003f8e70, 0xc0004189c0, 0xc0004189e0, 0xc00069af50)
        /home/chris/dev/git_work/distil/api/ws/pipeline.go:189 +0x56b
github.com/uncharted-distil/distil/api/ws.handleMessage(0xc000b74040, 0xc0003101e0, 0xc0003f8e70, 0xc0004189c0, 0xc0004189e0, 0xc0003f8ea0, 0xc00069af50)
        /home/chris/dev/git_work/distil/api/ws/pipeline.go:101 +0x285
created by github.com/uncharted-distil/distil/api/ws.handleSolutionMessage.func1
        /home/chris/dev/git_work/distil/api/ws/pipeline.go:92 +0x211
exit status 2
```

**Comment by cdbethune** [comment]
Note: the issue is restricted to working with pre-featurized cloned datasets that have been augmented with a new label.  The problem seems to be that on clone, the `LearningData` field is left pointing to the source of the clone.  If you select the new label as the target, it won't be available in the dataset which leads to a panic during splitting.
