### ISSUE TITLE
ROC AUC fails for random forest with remote sensing

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2305]
Random forest failing to generate a ROC AUC score for remote sensing problems:

```
44a52ae26928_distil_distil-auto-ml_1 | WARNING - 2021-02-23 19:13:15,784 - v-main-f55a555 - distil - Exception running task ID 9ee75972-c573-4bca-8d07-e261095edf3b: bad input shape (1423, 2)
44a52ae26928_distil_distil-auto-ml_1 | Traceback (most recent call last):
44a52ae26928_distil_distil-auto-ml_1 |   File "/app/main.py", line 138, in score_task
44a52ae26928_distil_distil-auto-ml_1 |     score_values, metric_used = scorer.run()
44a52ae26928_distil_distil-auto-ml_1 |   File "/app/processing/scoring.py", line 52, in run
44a52ae26928_distil_distil-auto-ml_1 |     return self.hold_out_score()
44a52ae26928_distil_distil-auto-ml_1 |   File "/app/processing/scoring.py", line 257, in hold_out_score
44a52ae26928_distil_distil-auto-ml_1 |     return ([self._score(metric, true_series, result_series, confidences)], metric)
44a52ae26928_distil_distil-auto-ml_1 |   File "/app/processing/scoring.py", line 119, in _score
44a52ae26928_distil_distil-auto-ml_1 |     score = self._roc_score(true, confidences)
44a52ae26928_distil_distil-auto-ml_1 |   File "/app/processing/scoring.py", line 104, in _roc_score
44a52ae26928_distil_distil-auto-ml_1 |     return metrics.roc_auc_score(true, confidences)
44a52ae26928_distil_distil-auto-ml_1 |   File "/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_ranking.py", line 390, in roc_auc_score
44a52ae26928_distil_distil-auto-ml_1 |     sample_weight=sample_weight)
44a52ae26928_distil_distil-auto-ml_1 |   File "/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_base.py", line 77, in _average_binary_score
44a52ae26928_distil_distil-auto-ml_1 |     return binary_metric(y_true, y_score, sample_weight=sample_weight)
44a52ae26928_distil_distil-auto-ml_1 |   File "/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_ranking.py", line 225, in _binary_roc_auc_score
44a52ae26928_distil_distil-auto-ml_1 |     sample_weight=sample_weight)
44a52ae26928_distil_distil-auto-ml_1 |   File "/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_ranking.py", line 771, in roc_curve
44a52ae26928_distil_distil-auto-ml_1 |     y_true, y_score, pos_label=pos_label, sample_weight=sample_weight)
44a52ae26928_distil_distil-auto-ml_1 |   File "/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_ranking.py", line 540, in _binary_clf_curve
44a52ae26928_distil_distil-auto-ml_1 |     y_score = column_or_1d(y_score)
44a52ae26928_distil_distil-auto-ml_1 |   File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 797, in column_or_1d
44a52ae26928_distil_distil-auto-ml_1 |     raise ValueError("bad input shape {0}".format(shape))
44a52ae26928_distil_distil-auto-ml_1 | ValueError: bad input shape (1423, 2)
distil            | [ Feb 23 19:13:18 ] [ INFO ] GRPC.STREAM_CLIENT [RECV] /Core/GetScoreSolutionResults
distil            | progress: <
distil            |   state: ERRORED
distil            |   status: "bad input shape (1423, 2)"
distil            | >
distil            |  (middleware/request_logger.go:99)
```

**Comment by cdbethune** [comment]
This appears to be an issue with the way the sklearn roc auc scoring expects data for binary classifiers.  Our random forest produces binary classification data s.t. each label is given a confidence:

```
      d3mIndex       label  confidence
0          625  no_hoppers    1.000000
1          625     hoppers    0.000000
2         2671  no_hoppers    1.000000
3         2671     hoppers    0.000000
4         2822  no_hoppers    0.989583
...        ...         ...         ...
1399        15     hoppers    0.598958
1400        46  no_hoppers    0.281250
1401        46     hoppers    0.718750
1402        27  no_hoppers    0.859375
1403        27     hoppers    0.140625
```
The roc auc scoring code expects a 1 dimensional array of predicted labels, and a one dimensional array of scores that correspond to each label.  The random forest primitive produces the output above, which results in a 2 dimensional array of values and 2 dimensional array of scores.  It needs to be collapsed down such that the label with the highest confidence is returned for each sample, rather than both.
