### ISSUE TITLE
Panic during outlier detection in prediction view

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2439]
The prediction view is attempting to run outlier detection on the prediction data and failing.  The prediction screen hasn't supported display of cluster, rank or outlier data in the past, although it may make sense to.

```
[ Mar 31 13:46:58 ] [ INFO ] GET /distil/config 200 in 0.38ms (api/middleware/request_logger.go:128)
[ Mar 31 13:46:58 ] [ INFO ] GET /distil/predictions/ca18796b-6a09-4053-805e-0d38ad45cd86 200 in 3.27ms (api/middleware/request_logger.go:128)
2021/03/31 13:46:58 http: panic serving [::1]:50918: runtime error: invalid memory address or nil pointer dereference
goroutine 64 [running]:
net/http.(*conn).serve.func1(0xc00044e460)
        /usr/lib/go/src/net/http/server.go:1824 +0x153
panic(0x1005580, 0x1a98150)
        /usr/lib/go/src/runtime/panic.go:971 +0x499
github.com/uncharted-distil/distil/api/task.OutlierDetection(0xc000b40c60, 0xc000172039, 0x9, 0x0, 0xc000b40c60, 0x0, 0x0, 0xc00029e000)
        /home/chris/dev/git_work/distil/api/task/outlier_detection.go:57 +0x1db
github.com/uncharted-distil/distil/api/routes.OutlierDetectionHandler.func1(0x12b22e0, 0xc000098140, 0xc0011e4600)
        /home/chris/dev/git_work/distil/api/routes/outlier_detecting.go:63 +0x12d
net/http.HandlerFunc.ServeHTTP(0xc0004e8030, 0x12b22e0, 0xc000098140, 0xc0011e4600)
        /usr/lib/go/src/net/http/server.go:2069 +0x44
goji.io/v3.dispatch.ServeHTTP(0x12b22e0, 0xc000098140, 0xc0011e4600)
        /home/chris/dev/go_workspace/pkg/mod/goji.io/v3@v3.0.0/dispatch.go:17 +0xbd
github.com/uncharted-distil/distil/api/middleware.Gzip.func1(0x7f16cc1bb9f8, 0xc0006c00c0, 0xc0011e4600)
        /home/chris/dev/git_work/distil/api/middleware/gzip.go:61 +0x282
net/http.HandlerFunc.ServeHTTP(0xc000548af8, 0x7f16cc1bb9f8, 0xc0006c00c0, 0xc0011e4600)
        /usr/lib/go/src/net/http/server.go:2069 +0x44
github.com/uncharted-distil/distil/api/middleware.Log.func1(0x12b21c0, 0xc0002d4000, 0xc0011e4600)
        /home/chris/dev/git_work/distil/api/middleware/log_http.go:37 +0x25f
net/http.HandlerFunc.ServeHTTP(0xc000548b10, 0x12b21c0, 0xc0002d4000, 0xc0011e4600)
        /usr/lib/go/src/net/http/server.go:2069 +0x44
goji.io/v3.(*Mux).ServeHTTP(0xc00054b800, 0x12b21c0, 0xc0002d4000, 0xc000540200)
        /home/chris/dev/go_workspace/pkg/mod/goji.io/v3@v3.0.0/mux.go:74 +0x1eb
net/http.serverHandler.ServeHTTP(0xc000253ea0, 0x12b21c0, 0xc0002d4000, 0xc000540200)
        /usr/lib/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc00044e460, 0x12b5ee0, 0xc0006c1f80)
        /usr/lib/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:3013 +0x39b
```

**Comment by phorne-uncharted** [comment]
I only had an issue on the refresh of the prediction page. The panic was caused because the target variable sent by the client was `Undefined`. I added a quick check to make sure the target variable exists, thereby flagging an error instead of panicking.

The underlying cause however still needs to be addressed. For some reason, on refresh of the page, the client does not have the variable info necessary to send the right target information down to the server.

**Comment by cdbethune** [comment]
This works for satellite image sets now.  There's a case with imported tabular data tracked under #3113 that doesn't seem to be the same root cause.
