### ISSUE TITLE
Join datasets ta2 incorrect types

### ISSUE THREAD

**Issue by Zac-hills** [uncharted-distil/distil#2502]
Datasets: acled_clean, world_bank_2018
columns: percent_female_employers, longitude
![Peek 2021-04-20 16-48](https://user-images.githubusercontent.com/25306965/115462279-77df0d00-a1f8-11eb-8f2e-a7d3a44a5ebc.gif)

Error:

`Traceback (most recent call last):
  File "/home/zhills/Programming/distil-auto-ml/venv/lib/python3.6/site-packages/d3m/runtime.py", line 1114, in _do_run_step
    self._run_step(step)
  File "/home/zhills/Programming/distil-auto-ml/venv/lib/python3.6/site-packages/d3m/runtime.py", line 1104, in _run_step
    self._run_primitive(step)
  File "/home/zhills/Programming/distil-auto-ml/venv/lib/python3.6/site-packages/d3m/runtime.py", line 979, in _run_primitive
    multi_call_result = self._call_primitive_method(primitive.fit_multi_produce, fit_multi_produce_arguments)
  File "/home/zhills/Programming/distil-auto-ml/venv/lib/python3.6/site-packages/d3m/runtime.py", line 1080, in _call_primitive_method
    raise error
  File "/home/zhills/Programming/distil-auto-ml/venv/lib/python3.6/site-packages/d3m/runtime.py", line 1076, in _call_primitive_method
    result = method(**arguments)
  File "/home/zhills/Programming/distil-primitives/distil/primitives/fuzzy_join.py", line 385, in fit_multi_produce
    right=right,
  File "/home/zhills/Programming/distil-auto-ml/venv/lib/python3.6/site-packages/d3m/primitive_interfaces/base.py", line 570, in _fit_multi_produce
    produce_results = self._multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, **kwargs)
  File "/home/zhills/Programming/distil-auto-ml/venv/lib/python3.6/site-packages/d3m/primitive_interfaces/base.py", line 466, in _multi_produce
    results.append(getattr(self, method_name)(timeout=timeout, iterations=iterations, **arguments))
  File "/home/zhills/Programming/distil-primitives/distil/primitives/fuzzy_join.py", line 268, in produce
    col_index,
  File "/home/zhills/Programming/distil-primitives/distil/primitives/fuzzy_join.py", line 506, in _create_numeric_merge_cols
    lambda x: cls._numeric_fuzzy_match(x, choices, accuracy)
  File "/home/zhills/Programming/distil-auto-ml/venv/lib/python3.6/site-packages/pandas/core/series.py", line 3630, in map
    new_values = super()._map_values(arg, na_action=na_action)
  File "/home/zhills/Programming/distil-auto-ml/venv/lib/python3.6/site-packages/pandas/core/base.py", line 1145, in _map_values
    new_values = map_f(values, mapper)
  File "pandas/_libs/lib.pyx", line 2329, in pandas._libs.lib.map_infer
  File "/home/zhills/Programming/distil-primitives/distil/primitives/fuzzy_join.py", line 506, in <lambda>
    lambda x: cls._numeric_fuzzy_match(x, choices, accuracy)
  File "/home/zhills/Programming/distil-primitives/distil/primitives/fuzzy_join.py", line 485, in _numeric_fuzzy_match
    distance = abs(match - num)
TypeError: unsupported operand type(s) for -: 'float' and 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 201, in fit_task
    outputs_to_expose=output_keys,
  File "/home/zhills/Programming/distil-auto-ml/processing/pipeline.py", line 520, in fit
    raise result.error
  File "/home/zhills/Programming/distil-auto-ml/venv/lib/python3.6/site-packages/d3m/runtime.py", line 1151, in _run
    self._do_run()
  File "/home/zhills/Programming/distil-auto-ml/venv/lib/python3.6/site-packages/d3m/runtime.py", line 1131, in _do_run
    self._do_run_step(step)
  File "/home/zhills/Programming/distil-auto-ml/venv/lib/python3.6/site-packages/d3m/runtime.py", line 1123, in _do_run_step
    ) from error
d3m.exceptions.StepFailedError: Step 6 for pipeline  failed.
DEBUG - 2021-04-20 16:48:18,769 - v-main-ef7d561 - distil.server.ServerServicer - GetFitSolutionResultsResponse: progress {
  state: ERRORED
  status: "Step 6 for pipeline  failed."
}`

**Comment by phorne-uncharted** [comment]
The join pipeline was missing the column parser, meaning the primitive was still dealing with string data rather than parsed floats.
