### ISSUE TITLE
Join between previously joined satellite + tabular and tabular failed

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2533]
Error during join.  The scenario was a join on previously joined satellite + land cover.  Came from TA2, but is likely an issue with data supplied by TA3:

```
 19%|#8        | 5/27 [00:07<00:31,  1.43s/it]
WARNING - 2021-04-23 15:03:14,719 - v-main-244eadd - distil - Exception running task ID dc3f70c9-eb2f-4e68-92d5-adc4a84df656: Step 5 for pipeline  failed.
Traceback (most recent call last):
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 1114, in _do_run_step
    self._run_step(step)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 1104, in _run_step
    self._run_primitive(step)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 979, in _run_primitive
    multi_call_result = self._call_primitive_method(primitive.fit_multi_produce, fit_multi_produce_arguments)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 1080, in _call_primitive_method
    raise error
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 1076, in _call_primitive_method
    result = method(**arguments)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/transformer.py", line 71, in fit_multi_produce
    return self._fit_multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, inputs=inputs)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/base.py", line 570, in _fit_multi_produce
    produce_results = self._multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, **kwargs)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/base.py", line 466, in _multi_produce
    results.append(getattr(self, method_name)(timeout=timeout, iterations=iterations, **arguments))
  File "/home/chris/dev/git_work/d3m-primitives/kf_d3m_primitives/remote_sensing/featurizer/remote_sensing_pretrained.py", line 210, in produce
    for image_batch in tqdm(image_loader):
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/tqdm/std.py", line 1130, in __iter__
    for obj in iterable:
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/chris/dev/environments/distil-auto-ml/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/chris/dev/git_work/d3m-primitives/kf_d3m_primitives/remote_sensing/featurizer/streaming_dataset.py", line 41, in __getitem__
    compressed_bytes = img.tobytes()
AttributeError: 'float' object has no attribute 'tobytes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 201, in fit_task
    outputs_to_expose=output_keys,
  File "/home/chris/dev/git_work/distil-auto-ml/processing/pipeline.py", line 520, in fit
    raise result.error
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 1151, in _run
    self._do_run()
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 1131, in _do_run
    self._do_run_step(step)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 1123, in _do_run_step
    ) from error
d3m.exceptions.StepFailedError: Step 5 for pipeline  failed.
DEBUG - 2021-04-23 15:03:17,653 - v-main-244eadd - distil.server.ServerServicer - GetFitSolutionResultsResponse: progress {
  state: ERRORED
  status: "Step 5 for pipeline  failed."
}
```

**Comment by phorne-uncharted** [comment]
I was unable to reproduce when using some test sentinel data for the first join and world bank joining on a numeric field for the second join. Sample data to reproduce may be helpful.

**Comment by cdbethune** [comment]
After all the fixes that have gone into joining, I've actually got it to complete with bofa sentinel joined with maize yield, followed by a join on moisture.  When I tried to use the dataset the following error is coming up, and the date facet shows an error:

```
failed to fetch variable extrema for summary
github.com/uncharted-distil/distil/api/model/storage/postgres.(*DateTimeField).fetchHistogramWithJoins
        /home/chris/dev/git_work/distil/api/model/storage/postgres/datetime.go:135
github.com/uncharted-distil/distil/api/model/storage/postgres.(*DateTimeField).fetchHistogram
        /home/chris/dev/git_work/distil/api/model/storage/postgres/datetime.go:123
github.com/uncharted-distil/distil/api/model/storage/postgres.(*DateTimeField).FetchSummaryData
        /home/chris/dev/git_work/distil/api/model/storage/postgres/datetime.go:89
github.com/uncharted-distil/distil/api/model/storage/postgres.(*Storage).fetchSummaryData
        /home/chris/dev/git_work/distil/api/model/storage/postgres/variable.go:127
github.com/uncharted-distil/distil/api/model/storage/postgres.(*Storage).FetchSummary
        /home/chris/dev/git_work/distil/api/model/storage/postgres/variable.go:149
github.com/uncharted-distil/distil/api/routes.VariableSummaryHandler.func1
        /home/chris/dev/git_work/distil/api/routes/variable_summaries.go:105
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go/src/net/http/server.go:2069
goji.io/v3.dispatch.ServeHTTP
        /home/chris/dev/go_workspace/pkg/mod/goji.io/v3@v3.0.0/dispatch.go:17
github.com/uncharted-distil/distil/api/middleware.Gzip.func1
        /home/chris/dev/git_work/distil/api/middleware/gzip.go:61
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go/src/net/http/server.go:2069
github.com/uncharted-distil/distil/api/middleware.Log.func1
        /home/chris/dev/git_work/distil/api/middleware/log_http.go:37
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go/src/net/http/server.go:2069
goji.io/v3.(*Mux).ServeHTTP
        /home/chris/dev/go_workspace/pkg/mod/goji.io/v3@v3.0.0/mux.go:74
net/http.serverHandler.ServeHTTP
        /usr/lib/go/src/net/http/server.go:2887
net/http.(*conn).serve
        /usr/lib/go/src/net/http/server.go:1952
runtime.goexit
        /usr/lib/go/src/runtime/asm_amd64.s:1371
failed to fetch summary data
github.com/uncharted-distil/distil/api/model/storage/postgres.(*Storage).fetchSummaryData
        /home/chris/dev/git_work/distil/api/model/storage/postgres/variable.go:129
github.com/uncharted-distil/distil/api/model/storage/postgres.(*Storage).FetchSummary
        /home/chris/dev/git_work/distil/api/model/storage/postgres/variable.go:149
github.com/uncharted-distil/distil/api/routes.VariableSummaryHandler.func1
        /home/chris/dev/git_work/distil/api/routes/variable_summaries.go:105
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go/src/net/http/server.go:2069
goji.io/v3.dispatch.ServeHTTP
        /home/chris/dev/go_workspace/pkg/mod/goji.io/v3@v3.0.0/dispatch.go:17
github.com/uncharted-distil/distil/api/middleware.Gzip.func1
        /home/chris/dev/git_work/distil/api/middleware/gzip.go:61
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go/src/net/http/server.go:2069
github.com/uncharted-distil/distil/api/middleware.Log.func1
        /home/chris/dev/git_work/distil/api/middleware/log_http.go:37
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go/src/net/http/server.go:2069
goji.io/v3.(*Mux).ServeHTTP
        /home/chris/dev/go_workspace/pkg/mod/goji.io/v3@v3.0.0/mux.go:74
net/http.serverHandler.ServeHTTP
        /usr/lib/go/src/net/http/server.go:2887
net/http.(*conn).serve
        /usr/lib/go/src/net/http/server.go:1952
runtime.goexit
        /usr/lib/go/src/runtime/asm_amd64.s:1371 (api/routes/error.go:39)

```

**Comment by cdbethune** [comment]
The above error seems to be a general problem with date time columns that have empty data in them, rather than a failure of chained joins.  #2681 has been opened to track that issue.
