### ISSUE TITLE
Remote Sensing Model Prediction

### ISSUE THREAD

**Issue by phorne-uncharted** [uncharted-distil/distil#2705]
Somehow, applying a remote sensing model created on locust tiny to the locust tiny dataset fails due to a feature mismatch. Specifically:
```
DEBUG - 2021-06-08 18:57:46,947 - v-main-1c4b616 - distil.primitives.ensemble_forest - Producing distil.primitives.ensemble_forest
WARNING - 2021-06-08 18:57:47,010 - v-main-1c4b616 - distil - Exception running task ID 21bf7171-6359-486e-829a-d67b42169eb7: Step 25 for pipeline d253fe12-3d1d-4d81-b1f5-77a122f84932 failed.
Traceback (most recent call last):
  File "/home/ubuntu/.env/distil/lib/python3.6/site-packages/d3m/runtime.py", line 1114, in _do_run_step
    self._run_step(step)
  File "/home/ubuntu/.env/distil/lib/python3.6/site-packages/d3m/runtime.py", line 1104, in _run_step
    self._run_primitive(step)
  File "/home/ubuntu/.env/distil/lib/python3.6/site-packages/d3m/runtime.py", line 992, in _run_primitive
    multi_call_result = self._call_primitive_method(primitive.multi_produce, multi_produce_arguments)
  File "/home/ubuntu/.env/distil/lib/python3.6/site-packages/d3m/runtime.py", line 1080, in _call_primitive_method
    raise error
  File "/home/ubuntu/.env/distil/lib/python3.6/site-packages/d3m/runtime.py", line 1076, in _call_primitive_method
    result = method(**arguments)
  File "/home/ubuntu/.env/distil/lib/python3.6/site-packages/d3m/primitive_interfaces/base.py", line 442, in multi_produce
    return self._multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, inputs=inputs)
  File "/home/ubuntu/.env/distil/lib/python3.6/site-packages/d3m/primitive_interfaces/base.py", line 466, in _multi_produce
    results.append(getattr(self, method_name)(timeout=timeout, iterations=iterations, **arguments))
  File "/home/ubuntu/git-projects/distil-primitives/distil/primitives/ensemble_forest.py", line 330, in produce
    result = self._model.predict(inputs.values)
  File "/home/ubuntu/git-projects/distil-primitives/distil/modeling/forest.py", line 147, in predict
    preds = [model.predict(X) for model in self._models]
  File "/home/ubuntu/git-projects/distil-primitives/distil/modeling/forest.py", line 147, in <listcomp>
    preds = [model.predict(X) for model in self._models]
  File "/home/ubuntu/git-projects/distil-primitives/distil/modeling/forest.py", line 57, in predict
    return self.model.predict(X)
  File "/home/ubuntu/.env/distil/lib/python3.6/site-packages/sklearn/ensemble/_forest.py", line 612, in predict
    proba = self.predict_proba(X)
  File "/home/ubuntu/.env/distil/lib/python3.6/site-packages/sklearn/ensemble/_forest.py", line 656, in predict_proba
    X = self._validate_X_predict(X)
  File "/home/ubuntu/.env/distil/lib/python3.6/site-packages/sklearn/ensemble/_forest.py", line 412, in _validate_X_predict
    return self.estimators_[0]._validate_X_predict(X, check_input=True)
  File "/home/ubuntu/.env/distil/lib/python3.6/site-packages/sklearn/tree/_classes.py", line 391, in _validate_X_predict
    % (self.n_features_, n_features))
ValueError: Number of features of the model must match the input. Model n_features is 2056 and input n_features is 2055
```

This error was obtained after applying clusters on the modelling dataset and filtering out `Pattern A`, then creating models and saving the first model. That saved model was then applied against the same initial dataset.

**Comment by phorne-uncharted** [comment]
This seems to be caused by the prefiltering step removing the polygon column from the dataset before the model gets created. When building the prediction dataset, the original dataset metadata gets used which still has that polygon column. Consequently, the input columns to the model and the prediction columns no longer match and the error occurs.
