### ISSUE TITLE
Models failing to run with error

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#2799]
Easiest reproduce case:

1. Select 196_auto_mpg
2. Set the target to `acceleration`
3. Set training features to `weight`, `horsepower`, `displacement`

Running the model returns the following on the server:
```
progress: <
  state: ERRORED
  status: "Not all problem description inputs could be applied to input datasets: {'dataset_id': 'pred_auto_196_test_2_1', 'targets': [{'target_index': 0, 'resource_id': 'learningData', 'column_index': 5, 'column_name': 'acceleration'}]}"
>
```

AutoML returns:

```
WARNING - 2021-07-28 11:44:49,036 - v-main-1708931 - distil - Exception running task ID 05bfd39f-2a32-4a19-9f00-59a9e5549cfc: Not all problem description inputs could be applied to input datasets: {'dataset_id': 'pred_auto_196_test_2_1', 'targets': [{'target_index': 0, 'resource_id': 'learningData', 'column_index': 5, 'column_name': 'acceleration'}]}
Traceback (most recent call last):
  File "main.py", line 201, in fit_task
    outputs_to_expose=output_keys,
  File "/home/chris/dev/git_work/distil-auto-ml/processing/pipeline.py", line 565, in fit
    outputs_to_expose=outputs_to_expose,
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 1493, in fit
    result = runtime.fit(inputs, outputs_to_expose=outputs_to_expose)
  File "/home/chris/dev/git_work/d3m/d3m/deprecate.py", line 140, in wrapper
    return f(*args, **kwargs)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 1251, in fit
    return self._run(inputs, metadata_base.PipelineRunPhase.FIT, outputs_to_expose or return_values)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 1145, in _run
    self._initialize_run_state(inputs, phase, outputs_to_expose)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 317, in _initialize_run_state
    self._initialize_data_values(inputs)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 301, in _initialize_data_values
    inputs=', '.join(str(problem_inputs[unmarked_problem_input]) for unmarked_problem_input in unmarked_problem_inputs),
d3m.exceptions.InvalidProblemError: Not all problem description inputs could be applied to input datasets: {'dataset_id': 'pred_auto_196_test_2_1', 'targets': [{'target_index': 0, 'resource_id': 'learningData', 'column_index': 5, 'column_name': 'acceleration'}]}
DEBUG - 2021-07-28 11:44:50,985 - v-main-1708931 - distil.server.ServerServicer - GetFitSolutionResultsResponse: progress {
  state: ERRORED
  status: "Not all problem description inputs could be applied to input datasets: {\'dataset_id\': \'pred_auto_196_test_2_1\', \'targets\': [{\'target_index\': 0, \'resource_id\': \'learningData\', \'column_index\': 5, \'column_name\': \'acceleration\'}]}"
}
```

**Comment by cdbethune** [comment]
Seems to longer be an issue.
