### ISSUE TITLE
Cannot save predictions as new dataset

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil#3110]
After training a hopper model using locust nano, I saved and applied it to a new dataset.  I then attempted to save the predictions as a new dataset with the "include data not used in model" button checked.  I get a large error dump containing many instances of the following:

```
2021/11/17 01:05:42 http: panic serving [::1]:56386: runtime error: index out of range [9] with length 9
goroutine 102 [running]:
net/http.(*conn).serve.func1(0xc0000c6aa0)
        /usr/lib/go/src/net/http/server.go:1824 +0x153
panic(0x10f1320, 0xc0003be240)
        /usr/lib/go/src/runtime/panic.go:971 +0x499
github.com/uncharted-distil/distil/api/model/storage/postgres.(*Storage).parseData(0xc00146c330, 0x12ff1d8, 0xc00117cc30, 0xc001c8a290, 0x1, 0x1, 0x12ff1d8, 0xc00117cc30)
        /home/chris/dev/git_work/distil/api/model/storage/postgres/dataset.go:287 +0x9d0
github.com/uncharted-distil/distil/api/model/storage/postgres.(*Storage).FetchResultDataset(0xc00146c330, 0xc0004681c0, 0x37, 0xc001c5e240, 0x32, 0xc000a8437a, 0x5, 0xc01367fc80, 0x7, 0x8, ...)
        /home/chris/dev/git_work/distil/api/model/storage/postgres/result.go:273 +0x885
github.com/uncharted-distil/distil/api/task.CreateDatasetFromResult(0xc000a842c0, 0xf, 0xc0004681c0, 0x37, 0xc000a843a0, 0xf, 0xc0013bbe00, 0x9, 0x10, 0xc000a8437a, ...)
        /home/chris/dev/git_work/distil/api/task/dataset.go:172 +0x525
github.com/uncharted-distil/distil/api/routes.CloningResultsHandler.func1(0x12f2c50, 0xc003dfe020, 0xc0013ba900)
        /home/chris/dev/git_work/distil/api/routes/clone.go:172 +0x465
net/http.HandlerFunc.ServeHTTP(0xc000209140, 0x12f2c50, 0xc003dfe020, 0xc0013ba900)
        /usr/lib/go/src/net/http/server.go:2069 +0x44
goji.io/v3.dispatch.ServeHTTP(0x12f2c50, 0xc003dfe020, 0xc0013ba900)
        /home/chris/dev/go_workspace/pkg/mod/goji.io/v3@v3.0.0/dispatch.go:17 +0xbd
github.com/uncharted-distil/distil/api/middleware.Gzip.func1(0x7ff1ec267938, 0xc009726300, 0xc0013ba900)
        /home/chris/dev/git_work/distil/api/middleware/gzip.go:61 +0x282
net/http.HandlerFunc.ServeHTTP(0xc000506408, 0x7ff1ec267938, 0xc009726300, 0xc0013ba900)
        /usr/lib/go/src/net/http/server.go:2069 +0x44
github.com/uncharted-distil/distil/api/middleware.Log.func1(0x12f2b30, 0xc0003c2000, 0xc0013ba900)
        /home/chris/dev/git_work/distil/api/middleware/log_http.go:37 +0x25f
net/http.HandlerFunc.ServeHTTP(0xc000506420, 0x12f2b30, 0xc0003c2000, 0xc0013ba900)
        /usr/lib/go/src/net/http/server.go:2069 +0x44
goji.io/v3.(*Mux).ServeHTTP(0xc00004cb80, 0x12f2b30, 0xc0003c2000, 0xc001f54200)
        /home/chris/dev/go_workspace/pkg/mod/goji.io/v3@v3.0.0/mux.go:74 +0x1eb
net/http.serverHandler.ServeHTTP(0xc000654000, 0x12f2b30, 0xc0003c2000, 0xc001f54200)
        /usr/lib/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0000c6aa0, 0x12f6fc0, 0xc00014e0c0)
        /usr/lib/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:3013 +0x39b
```

**Comment by cdbethune** [comment]
fixed by #3130, #3131
